#!/usr/bin/env sh

# mise description="build docker image for the data provider"
# mise tools=["rust"]

cd $root/platform/dataprovider

cp $root/Cargo.lock .

IMAGE=pocketsizefund/dataprovider

VERSION=$(cargo pkgid | awk -F# '{print $NF}')

docker build \
    --tag $IMAGE:latest \
    --tag $IMAGE:$VERSION \
    --platform $PLATFORM \
    .
