#!/usr/bin/env sh

# mise description="build docker image for the data provider"
# mise tools=["rust"]

IMAGE=pocketsizefund/dataprovider

VERSION=1.0.0

docker build \
    --file platform/dataprovider/Dockerfile \
    --tag $IMAGE:latest \
    --tag $IMAGE:$VERSION \
    --platform $PLATFORM \
    .
