#!/usr/bin/env sh

# mise description="deploy data provider to cluster"
# mise tools=["kubectl"]

cd $root/platform/dataprovider
kubectl apply -f manifest.yaml --namespace development
kubectl apply -f manifest.yaml --namespace paper 
kubectl apply -f manifest.yaml --namespace live
