#!/usr/bin/env sh

# mise description="remove data provider from cluster"
# mise tools=["kubectl"]

cd $root/platform/dataprovider
kubectl destroy -f manifest.yaml --namespace development
kubectl destroy -f manifest.yaml --namespace paper 
kubectl destroy -f manifest.yaml --namespace live
