#!/usr/bin/env sh

# mise description="push data provider image to docker hub"
# mise depends=["platform:dataprovider:build"]

cd $root/platform/dataprovider

IMAGE=pocketsizefund/dataprovider
VERSION=$(cargo pkgid | awk -F# '{print $NF}')

docker push $IMAGE:latest
docker push $IMAGE:$VERSION
