#!/usr/bin/env sh

# mise description="push data provider image to docker hub"
# mise depends=["platform:dataprovider:build"]

cd platform/dataprovider

IMAGE=pocketsizefund/data-provider
VERSION=$(poetry version -s)

docker push $IMAGE:latest
docker push $IMAGE:$VERSION
