[package]
name = "compliance"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
cloudevents-sdk = { version = "0.7.0", features = ["actix", "actix-web", "reqwest"] }
env_logger = "0.11.5"
pocketsizefund = { version = "0.1.2", path = "../../libraries/rust", features = ["events", "web"] }
tokio = { version = "1.40.0", features = ["full"] }

[dev-dependencies]
chrono = "0.4.38"
lazy_static = "1.5.0"
reqwest = "0.12.7"
serde_json = "1.0.127"
