[package]
name = "broker"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
apca = "0.29.0"
tokio = { version = "1.39.1", features = ["macros", "rt-multi-thread", "tokio-macros", "tracing"] }
