FROM python:3.11.6

RUN pip3 install sagemaker-training

WORKDIR /opt/ml/code

COPY requirements.txt .

COPY pkg/storage pkg/storage

COPY exp/lstm/entrypoint_train.py .

ENV SAGEMAKER_PROGRAM entrypoint_train.py
