FROM python:3.11.6

COPY exp/lstm/requirements_predict.txt requirements.txt

COPY pkg/storage pkg/storage

COPY pkg/data pkg/data

COPY exp/lstm/entrypoint_predict.py .

COPY exp/lstm/entrypoint_helpers.py .

# conditionally copy model artifact for local builds
COPY lstm.kera[s] model/

RUN pip3 install --no-cache-dir -r requirements.txt

RUN pip3 install sagemaker-inference Flask

EXPOSE 8080

ENTRYPOINT ["python3", "entrypoint_predict.py"]

CMD ["serve"]