FROM python:3.11.6

COPY exp/lstm/requirements_evaluate.txt requirements.txt

COPY exp/lstm/entrypoint_evaluate.py .

RUN pip3 install --no-cache-dir -r requirements.txt

ENTRYPOINT ["python3", "entrypoint_evaluate.py"]
