#!/usr/bin/env sh

# mise description="build docker image for price model"

cd $root/platform/pricemodel

IMAGE=pocketsizefund/price-model
VERSION=$(awk -F '[="]' '/^[[:space:]]*version/ {gsub(/^[[:space:]]+|[[:space:]]+$/, "", $3); print $3}' pyproject.toml)
echo "using version $VERSION"

docker build -t $IMAGE:latest \
	-t $IMAGE:$VERSION \
	--platform $PLATFORM \
	.