#!/usr/bin/env sh

# mise description="deploy price model to cluster"
# mise tools=["kubectl"]

cd $root/platform/pricemodel
kubectl apply -f manifest.yaml --namespace development
kubectl apply -f manifest.yaml --namespace paper 
kubectl apply -f manifest.yaml --namespace live
