#!/usr/bin/env sh

# mise description="remove price model from cluster"
# mise tools=["kubectl"]

cd $root/platform/pricemodel
kubectl down -f manifest.yaml --namespace development
kubectl down -f manifest.yaml --namespace paper 
kubectl down -f manifest.yaml --namespace live
