#!/usr/bin/env sh

# mise description="push price model image to docker hub"
# mise depends=["platform:pricemodel:build"]

cd $root/platform/pricemodel

IMAGE=pocketsizefund/price-model
VERSION=$(awk -F '[="]' '/^[[:space:]]*version/ {gsub(/^[[:space:]]+|[[:space:]]+$/, "", $3); print $3}' pyproject.toml)

docker push $IMAGE:latest
docker push $IMAGE:$VERSION
