#!/usr/bin/env sh

# mise description="build docker image for chronos"
# mise tools=["rust"]

IMAGE=pocketsizefund/chronos

VERSION=1.0.0

docker build \
    --file platform/chronos/Dockerfile \
    --tag $IMAGE:latest \
    --tag $IMAGE:$VERSION \
    --platform $PLATFORM \
    .
