#!/usr/bin/env sh

# mise description="build docker image for chronos"
# mise tools=["cargo"]

cd $root/platform/chronos

IMAGE=pocketsizefund/chronos
VERSION=$(cargo pkgid | awk -F# '{print $NF}')

echo building $IMAGE:$VERSION on $PLATFORM

docker build -t $IMAGE:latest -t $IMAGE:$VERSION --platform $PLATFORM .
