#!/usr/bin/env sh

# mise description="ping the chronos service for testing"
# mise tools=["httpie"]

cd $root/platform/chronos

http POST http://127.0.0.1:8080/market-open-check \
    Content-Type:application/cloudevents+json \
    ce-specversion:1.0 \
    message="Good morning" \
    specversion="1.0" \
    id="1" \
    type="dev.knative.example" \
    source="localhost:1000"
