#!/usr/bin/env sh

# mise description="push price model image to docker hub"
# mise depends=["platform:chronos:build"]

cd $root/platform/chronos

IMAGE=pocketsizefund/chronos
VERSION=$(cargo pkgid | cut -d'#' -f2)

echo "building $IMAGE:$VERSION on $PLATFORM"

docker push $IMAGE:latest
docker push $IMAGE:$VERSION
