#!/usr/bin/env sh

# mise description="push price model image to docker hub"
# mise depends=["platform:chronos:build"]

cd $root/platform/chronos

IMAGE=pocketsizefund/chronos
VERSION=$(cargo pkgid | awk -F# '{print $NF}')

docker push $IMAGE:latest
docker push $IMAGE:$VERSION
