#!/usr/bin/env sh

# mise description="build docker image for the metrics reporter"
# mise tools=["poetry"]

IMAGE=pocketsizefund/metricsreporter

VERSION=1.0.0

docker build \
    --file platform/metricsreporter/Dockerfile \
    --tag $IMAGE:latest \
    --tag $IMAGE:$VERSION \
    --platform $PLATFORM \
    .
