#!/usr/bin/env sh

# mise description="push metrics reporter image to docker hub"
# mise depends=["platform:metricsreporter:build"]

cd $root/platform/metricsreporter

IMAGE=pocketsizefund/metricsreporter

VERSION=$(cargo pkgid | awk -F# '{print $NF}')

docker push $IMAGE:latest

docker push $IMAGE:$VERSION
