#!/usr/bin/env sh

# mise description="deploy price model to all environments"
# mise depends=["platform:pricemodel:deploy:development", "platform:pricemodel:deploy:paper", "platform:pricemodel:deploy:live"]
