#!/usr/bin/env sh

# mise description="deploy position manager to development environment"
# mise tools=["poetry"]

cd $root/platform/pricemodel
kubectl apply -f manifest.yaml --namespace development
