#!/usr/bin/env sh

# mise description="run python code quality checks across the full repository"

uv run ruff check \
    --output-format=github \
    --config pyproject.toml \
    .

# cannot be configured in pyproject.toml
uv run vulture \
    --min-confidence 80 \
    --exclude '.venv,target' \
    .

uv run ruff format
