#!/usr/bin/env sh

# mise description="publish the pocketsizefund python package to PyPI registry"
# mise depends=["libraries:python:build"]
# mise tools=["poetry"]

cd $root/libraries/python/pocketsizefund
poetry config pypi-token.pypi $PYPI_TOKEN
poetry publish

