#!/usr/bin/env sh

# mise description="unit tests for the pocketsizefund python package"

cd $root/libraries/python
uv run coverage run --parallel-mode --module pytest
uv run coverage combine
uv run coverage report --omit='tests/*'
uv run coverage xml --omit='tests/*'
rm -rf .coverage
mv coverage.xml $root
