[tasks."python:format"]
description="format python code"
run = "ruff format"

[tasks."python:dead-code"]
depends = ["python:format"]
description="check for dead python code"
run = """
vulture \
    --min-confidence 80 \
    --exclude '.flox,.venv,target' \
    .
"""

[tasks."python:lint"]
depends = ["python:dead-code"]
description="run python code quality checks across the full repository"
run = """
ruff check \
    --output-format=github \
    .
"""

[tasks."haskell:format"]
description = "lint haskell code"
run = "ormolu --mode inplace $(find . -name '*.hs')"

[tasks."haskell:lint"]
description = "lint haskell code"
depends = ["haskell:format"]
run = "hlint ."

[tasks."haskell:test"]
description = "run haskell tests"
run = "cd platform && stack test"

[tasks."platform:run"]
description = "run platform in docker compose"
run = """
cd platform
docker compose up
"""

[tasks."platform:build"]
description = "build platform image to dockerhub"
run = """
TIMESTAMP=$(date +%Y%m%d) 
cd platform
docker build \
    --platform linux/amd64 \
    -t pocketsizefund/platform:latest \
    -t pocketsizefund/platform:${TIMESTAMP} \
    .
"""

[tasks."platform:push"]
description = "push platform image to dockerhub"
depends = ["platform:build"]
run = """
TIMESTAMP=$(date +%Y%m%d) 
cd platform
docker push pocketsizefund/platform:latest
docker push pocketsizefund/platform:${TIMESTAMP}
"""

[tasks."infrastructure:up"]
description = "launch infrastructure"
run = "cd infrastructure && uv run pulumi up"

<<<<<<< Updated upstream
[tasks."format"]
description = "format entire codebase"
depends = ["python:lint", "haskell:lint"]

[tasks."lint"]
description = "lint entire codebase"
depends = ["format"]

[tasks."test"]
description = "run all tests"
depends = ["haskell:test"]
=======

[tasks."workflows:register"]
description = "register flyte workflows with union"
run = "uv run union register workflows"
>>>>>>> Stashed changes
