[tasks."python:check"]
description="run python code quality checks across the full repository"
run = """
uvx ruff check \
    --output-format=github \
    .

"""

[tasks."python:dead-code"]
description="check for dead python code"
run = """
uvx vulture \
    --min-confidence 80 \
    --exclude '.venv,target' \
    .
"""

[tasks."python:format"]
description="format python code"
run = "uvx ruff format"

[tasks."python:lint"]
depends = ["python:check", "python:dead-code", "python:format"]
description="run python code quality checks across the full repository"

[tasks."platform:run"]
description = "run platform in docker compose"
run = "cd platform && docker compose up"

[tasks."platform:build"]
description = "build platform image to dockerhub"
run = """
TIMESTAMP=$(date +%Y%m%d) 
cd platform
docker build \
    --platform linux/amd64 \
    -t pocketsizefund/platform:latest \
    -t pocketsizefund/platform:${TIMESTAMP} \
    .
"""

[tasks."platform:push"]
description = "push platform image to dockerhub"
depends = ["platform:build"]
run = """
TIMESTAMP=$(date +%Y%m%d) 
cd platform
docker push pocketsizefund/platform:latest
docker push pocketsizefund/platform:${TIMESTAMP}
"""

[tasks."infrastructure:up"]
description = "launch infrastructure"
run = "cd infrastructure && uv run pulumi up"
