[workspace]
resolver = "2"

members = [ 
    "libraries/rust",
    "platform/newsfeed",
    "platform/discord",
    "platform/newsfeed",
    "platform/discord", "pocket",
    "platform/chronos",
    "pocket"
, "infrastructure"]
