[workspace]
resolver = "2"

members = [
    # "libraries/rust",
    "platform/broker",
    "platform/chronos",
    "platform/discordbot",
    "platform/datacollector", 
    "platform/dataprovider",
    "platform/scrum",
    "platform/trader",
]
