[workspace]
resolver = "2"

members = [
    "libraries/rust",
    "platform/broker",
    "platform/chronos",
    "platform/discord",
    "platform/datacollector", 
    "platform/dataprovider",
    "platform/newsfeed", "platform/compliance",
]
