[workspace]
resolver = "2"

members = [ 
    "libraries/rust",
    "platform/newsfeed",
    "platform/discord",
    "platform/newsfeed",
    "platform/discord",
    # "platform/chronos",
]

exclude = ["platform/chronos", "libraries/rust/data"]
