
services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
       - .:/tests
    command:
      - /bin/sh
      - -euxc
      - |
        uv run coverage run --parallel-mode -m pytest && \
        uv run coverage combine && \
        uv run coverage report && \
        uv run coverage xml

