FROM python:3.13

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

RUN apt-get update && apt-get install -y \
    build-essential \
    clang \
    libc6-dev \
    linux-libc-dev \
    && rm -rf /var/lib/apt/lists/*

ENV PYTEST_ADDOPTS="--rootdir=/tests"

ENV PYTHON=1

WORKDIR /tests

COPY pyproject.toml uv.lock ./

COPY applications/datamanager/pyproject.toml ./applications/datamanager/

COPY applications/positionmanager/pyproject.toml ./applications/positionmanager/

COPY applications/predictionengine/pyproject.toml ./applications/predictionengine/

COPY infrastructure/pyproject.toml ./infrastructure/

COPY applications/models/pyproject.toml ./applications/models/

COPY libraries/ ./libraries/

RUN uv sync --all-packages --dev

COPY applications/ ./applications/

RUN mkdir -p /tests/coverage_output
