---
name: pocketsizefund-tests

services:
  tests:
    image: pocketsizefund-tests:latest
    build:
      context: .
      dockerfile: Dockerfile.tests
      tags:
        - pocketsizefund-tests:latest
    volumes:
      - ./coverage_output:/tests/coverage_output # mounted for coverage output
    command:
      - /bin/sh
      - -euxc
      - |
        uv run coverage run --parallel-mode -m pytest && \
        uv run coverage combine && \
        uv run coverage report && \
        uv run coverage xml -o /tests/coverage_output/.python_coverage.xml
