services:
  tradeexecutor:
    build:
      context: ../..
      dockerfile: platform/tradeexecutor/Dockerfile
    platform: linux/amd64
    environment:
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_API_SECRET=${ALPACA_API_SECRET}
      - DARQUBE_API_KEY=${DARQUBE_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - ENVIRONMENT=development
      - SERVER_PORT=8080
    ports:
      - 8080:8080
    volumes:
      - ./platform/tradeexecutor:/app/platform/tradeexecutor
      - ./libraries/rust:/app/libraries/rust
