#!/usr/bin/env sh

# mise description="deploy position manager to paper environment"
# mise depends=["platform:discord:deploy:development", "platform:discord:deploy:paper", "platform:discord:deploy:live"]
