#!/usr/bin/env sh

# mise description="build docker image for the data fetcher"
# mise tools=["rust"]

IMAGE=pocketsizefund/datafetcher

VERSION=1.0.0

docker build \
    --file platform/datafetcher/Dockerfile \
    --tag $IMAGE:latest \
    --tag $IMAGE:$VERSION \
    --platform $PLATFORM \
    .
