#!/usr/bin/env sh

# mise description="push data fetcher image to docker hub"
# mise depends=["platform:datafetcher:build"]

cd $root/platform/datafetcher

IMAGE=pocketsizefund/datafetcher
VERSION=$(cargo pkgid | awk -F# '{print $NF}')

docker push $IMAGE:latest
docker push $IMAGE:$VERSION
