[package]
name = "positionmanager"
version = "1.0.0"
edition = "2021"
license = "MIT"

[dependencies]
actix-web = "4.9.0"
env_logger = "0.11.5"
cloudevents-sdk = { version = "0.7.0", features = [
    "actix",
    "actix-http",
    "actix-web",
    "http-binding",
    "http-body",
    "reqwest",
] }
pocketsizefund = { path = "../../libraries/rust", features = [
    "trade",
    "events",
    "data",
] }
reqwest = { version = "0.12.7", features = ["json"] }
url = "2.5.2"
serde_json = "1.0.117"
chrono = { version = "0.4.38", features = ["serde"] }
serde = { version = "1.0.204", features = ["derive"] }
rand = "0.8.5"
mockall = "0.11"
async-trait = "0.1.82"

[dev-dependencies]
tokio = { version = "1.38.1", features = ["full", "test-util"] }
mockito = "1.4.0"
