services:
  positionmanager:
    build:
      context: .
      tags:
        - "positionmanager:latest"
    platform: linux/amd64
    ports:
      - 8080:8080
    environment:
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_API_SECRET=${ALPACA_API_SECRET}
