services:
  positionmanager:
    build:
      context: .
      tags:
        - "positionmanager:latest"
    platform: linux/amd64
    ports:
      - 8080:8080
    environment:
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_API_SECRET=${ALPACA_API_SECRET}
      - ENVIRONMENT=${ENVIRONMENT}
      - MODEL_COUNT=${MODEL_COUNT}
      - CONFIDENCE_LEVEL=${CONFIDENCE_LEVEL}
      - RISK_THRESHOLD=${RISK_THRESHOLD}
