services:
  positionmanager:
    build:
      context: .
    platform: linux/amd64
    environment:
      - SENTRY_DSN
      - DARQUBE_API_KEY
      - ALPACA_API_KEY
      - ALPACA_API_SECRET
      - ALPHA_VANTAGE_API_KEY
      - IS_PAPER
      - KAFKA_BOOTSTRAP_SERVER
      - KAFKA_SASL_MECHANISM
      - KAFKA_SECURITY_PROTOCOL
      - KAFKA_USERNAME
      - KAFKA_PASSWORD
      - EDGAR_USER_AGENT
      - MODEL_FILE_NAME
      - DARQUBE_API_KEY
      - ALPACA_API_KEY
      - ALPACA_API_SECRET
      - ALPHA_VANTAGE_API_KEY
      - EDGAR_USER_AGENT
      - MODEL_FILE_NAME
