services:
  positionmanager:
    build:
      context: ../..
      dockerfile: platform/positionmanager/Dockerfile
    platform: linux/amd64
    environment:
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_API_SECRET=${ALPACA_API_SECRET}
      - DARQUBE_API_KEY=${DARQUBE_API_KEY}
      - IS_PRODUCTION=false
      - ENVIRONMENT=development
      - SERVER_PORT=8080
    ports:
      - 8080:8080
    volumes:
      - ./platform/positionmanager:/app/platform/positionmanager
      - ./libraries/rust:/app/libraries/rust
