apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: position-manager
  template:
    metadata:
      labels:
        app: position-manager
    spec:
      containers:
        - name: position-manager
          image: pocketsizefund/position-manager:0.1.6 # live
          image: pocketsizefund/position-manager:latest # development, paper
          imagePullPolicy: IfNotPresent
          env:
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: sentry_dsn
            - name: DARQUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: darqube_api_key
            - name: ALPACA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: alpaca_api_key
            - name: ALPACA_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: alpaca_api_secret
            - name: ALPHA_VANTAGE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: alpha_vantage_api_key
            - name: KAFKA_BOOTSTRAP_SERVER
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: kafka_bootstrap_server
            - name: KAFKA_SASL_MECHANISM
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: kafka_sasl_mechanism
            - name: KAFKA_SECURITY_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: kafka_security_protocol
            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: kafka_username
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: kafka_password
            - name: EDGAR_USER_AGENT
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: edgar_user_agent
            - name: MODEL_FILE_NAME
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: model_file_name
            - name: IS_PAPER
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: is_paper
