apiVersion: batch/v1
kind: CronJob
metadata:
  name: position-manager
spec:
  schedule: "0 10,12,15 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: position-manager
              image: pocketsizefund/position-manager:0.1.0
              imagePullPolicy: IfNotPresent # or Never
              command: ["python", "main.py"]
              env:
                - name: SENTRY_DSN
                  valueFrom:
                    secretKeyRef:
                      name: platform
                      key: sentry_dsn
                - name: DARQUBE_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: platform
                      key: darqube_api_key
                - name: ALPACA_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: platform
                      key: alpaca_api_key
                - name: ALPACA_API_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: platform
                      key: alpaca_api_secret
                - name: ALPHA_VANTAGE_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: platform
                      key: alpha_vantage_api_key
          restartPolicy: OnFailure
