#!/usr/bin/env sh

# mise description="build docker image for discordot bot"
# mise tools=["cargo"]

cd $root/platform/discordbot

IMAGE=pocketsizefund/discordbot
VERSION=$(cargo pkgid | awk -F# '{print $NF}')

echo building $IMAGE:$VERSION on $PLATFORM

docker buildx -t $IMAGE:latest -t $IMAGE:$VERSION --platform $PLATFORM .
