#!/usr/bin/env sh

# mise description="push price model image to docker hub"
# mise depends=["platform:discordbot:build"]

cd $root/platform/discordbot

IMAGE=pocketsizefund/discordbot
VERSION=$(cargo metadata --format-version 1 | jq -r '.packages[0].version')

docker push $IMAGE:latest
docker push $IMAGE:$VERSION
