#!/usr/bin/env sh

# mise description="sync cluster secrets with local kube config in deveopment namespace"
# mise depends=["infrastructure:k8s:secrets:development:sync", "infrastructure:k8s:secrets:paper:sync", "infrastructure:k8s:secrets:live:sync"]
# mise tools=["jq", "yq", "kubectl"]
