FROM public.ecr.aws/lambda/python:3.11-arm64

ARG FUNCTION_NAME

RUN yum install -y gcc python3-devel

COPY cmd/lambda/requirements.txt ${LAMBDA_TASK_ROOT}

RUN pip3 install --requirement requirements.txt --target "${LAMBDA_TASK_ROOT}"

COPY pkg ${LAMBDA_TASK_ROOT}/pkg

COPY cmd/lambda/${FUNCTION_NAME}/main.py ${LAMBDA_TASK_ROOT}

ENV S3_DATA_BUCKET_NAME=""

ENV ALPACA_API_KEY=""

ENV ALPACA_API_SECRET=""

ENV DARQUBE_API_KEY=""

ENV IS_PAPER=""

ENV MODEL_ENDPOINT_NAME=""

CMD [ "main.handler" ]
