services:
  discordbot:
    build:
      context: ../..
      dockerfile: platform/discordbot/Dockerfile
    platform: linux/amd64
    ports:
      - 8080:8080
    environment:
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    volumes:
      - ./platform/discordbot:/app/platform/discordbot
      - ./libraries/rust:/app/libraries/rust
