name: Prediction engine integration tests

services:
  predictionengine:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DATAMANAGER_BASE_URL=${DATAMANAGER_BASE_URL}
      - POSITIONMANAGER_BASE_URL=${POSITIONMANAGER_BASE_URL}
    volumes:
      - ./:/app/predictionengine
      - ~/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 1s
