FROM python:3.11.6

COPY ml/lstm/requirements_predict.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY pkg/storage pkg/storage

COPY pkg/data pkg/data

COPY ml/lstm/entrypoint_predict.py .

COPY ml/lstm/entrypoint_helpers.py .

# conditionally copy model artifact for local builds
COPY lstm.kera[s] model/

# conditionally copy scalers artifact for local builds
COPY scalers.pk[l] model/

EXPOSE 8080

ENTRYPOINT ["python3", "entrypoint_predict.py"]

CMD ["serve"]