[package]
name = "datacollector"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
actix-web = "4"
chrono = { version = "0.4.38", features = ["serde"] }
pocketsizefund = { git = "https://github.com/pocketsizefund/pocketsizefund.git", branch = "master", features = ["data"] }