services:
  datacollector:
    build:
      context: .
    platform: linux/amd64
    environment:
      - ALPACA_API_KEY
      - ALPACA_API_SECRET
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - S3_DATA_BUCKET_NAME
      - SERVER_PORT=8080
