#!/usr/bin/env sh

# mise description="build docker image for the scrum master"
# mise tools=["poetry"]

cd $root/platform/scrum

IMAGE=pocketsizefund/scrum
VERSION=$(cargo pkgid | awk -F# '{print $NF}')

docker build -t $IMAGE:latest -t $IMAGE:$VERSION --platform $PLATFORM .
