#!/usr/bin/env sh

# mise description="push scrum master image to docker hub"
# mise depends=["platform:scrum:build"]

cd platform/scrum

IMAGE=pocketsizefund/scrum
VERSION=$(cargo pkgid | awk -F# '{print $NF}')

docker push $IMAGE:latest
docker push $IMAGE:$VERSION
