#!/usr/bin/env sh

# mise description="build docker image for the data collector"
# mise tools=["rust"]

IMAGE=pocketsizefund/datacollector

VERSION=1.0.0

docker build \
    --file platform/datacollector/Dockerfile \
    --tag $IMAGE:latest \
    --tag $IMAGE:$VERSION \
    --platform $PLATFORM \
    .
