#!/usr/bin/env sh

# mise description="deploy data collector to cluster"
# mise tools=["kubectl"]

cd $root/platform/datacollector
kubectl apply -f manifest.yaml --namespace development
kubectl apply -f manifest.yaml --namespace paper 
kubectl apply -f manifest.yaml --namespace live
