#!/usr/bin/env sh

# mise description="push data collector image to docker hub"
# mise depends=["platform:datacollector:build"]

cd $root/platform/datacollector

IMAGE=pocketsizefund/datacollector

VERSION=$(cargo pkgid | awk -F# '{print $NF}')

docker push $IMAGE:latest

docker push $IMAGE:$VERSION
