FROM public.ecr.aws/lambda/python:3.11-arm64

RUN yum clean all

RUN yum install -y gcc python3-devel

COPY cmd/lambda/postperformance/requirements.txt ${LAMBDA_TASK_ROOT}/requirements.txt

RUN pip3 install --requirement requirements.txt --target "${LAMBDA_TASK_ROOT}"

COPY pkg/trade/trade.py ${LAMBDA_TASK_ROOT}/pkg/trade/trade.py

COPY pkg/twitter/twitter.py ${LAMBDA_TASK_ROOT}/pkg/twitter/twitter.py

COPY cmd/lambda/postperformance/main.py ${LAMBDA_TASK_ROOT}/main.py

ENV DARQUBE_API_KEY=""

ENV ALPACA_API_KEY=""

ENV ALPACA_API_SECRET=""

ENV IS_PAPER=""

ENV TWITTER_API_KEY=""

ENV TWITTER_API_SECRET=""

ENV TWITTER_ACCESS_TOKEN=""

ENV TWITTER_ACCESS_TOKEN_SECRET=""

ENV IMAGE_FILES_PATH=""

CMD [ "main.handler" ]
