#!/usr/bin/env sh

# mise description="launch infrastructure"
# mise tools=["docker"]

cd $root/infrastructure

docker run --rm -it \
  --platform $PLATFORM \
  --env PULUMI_ACCESS_TOKEN \
  pocketsizefund/infrastructure pulumi up \
  --stack $PULUMI_STACK --yes
