FROM python:3.11.6

COPY cmd/script/evaluatemodel/requirements.txt .

RUN pip3 install -r requirements.txt

COPY pkg/storage/storage.py pkg/storage/

COPY pkg/model/model.py pkg/model/

COPY cmd/script/evaluatemodel/entrypoint.py .

ENTRYPOINT ["python3", "entrypoint.py"]
