[package]
name = "trader"
version = "202409.15.1"
edition = "2021"
license = "MIT"

[lib]
name = "trader"
path = "src/lib.rs"

[[bin]]
name = "trader"
path = "src/main.rs"

[dependencies]
actix-web = "4.9.0"
anyhow = { version = "1.0.89", features = ["backtrace"] }
apca = "0.29.0"
chrono = "0.4.38"
cloudevents-sdk = { version = "0.7.0", features = ["actix", "actix-web", "http-binding", "http-body", "reqwest"] }
env_logger = "0.11.5"
num-decimal = { version = "0.2.5", default-features = false, features = ["num-v04", "serde"] }
pocketsizefund = { version = "0.1.3", features = ["events", "web"] }
rand = "0.8.5"
reqwest = "0.12.7"
rust_decimal = "1.36.0"
rust_decimal_macros = "1.36.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["full"] }
tracing = { version = "0.1.40", features = ["async-await"] }
tracing-subscriber = { version = "0.3.18", features = ["chrono", "env-filter"] }
uuid = { version = "1.10.0", features = ["v4"] }
