services:
  trader:
    build:
      context: .
      tags:
        - "trader:latest"
    ports:
      - 8081:8081
    platform: linux/amd64
    environment:
      - PORT=8081
      - ALPACA_API_KEY
      - ALPACA_API_SECRET
      - APCA_API_BASE_URL
      - APCA_API_KEY_ID
      - APCA_API_SECRET_KEY
      - PRICE_MODEL_URL=http://pricemodel:8080
      - DISCORD_BOT_URL=http://discordbot:8082
    depends_on:
      - pricemodel
      - discordbot

  pricemodel:
    image: pocketsizefund/price-model:latest
    ports:
      - 8080:8080
    environment:
      - ALPACA_API_KEY
      - ALPACA_API_SECRET
      - DARQUBE_API_KEY
      - ALPHA_VANTAGE_API_KEY
      - APCA_API_BASE_URL
      - APCA_API_KEY_ID
      - APCA_API_SECRET_KEY
      - ALPACA_API_BASE_URL

  discordbot:
    image: pocketsizefund/discordbot:latest
    ports:
      - 8082:8082
    environment:
      - PORT=8082
      - DISCORD_WEBHOOK_URL
      - ALPACA_API_KEY
      - ALPACA_API_SECRET
      - DARQUBE_API_KEY
      - ALPHA_VANTAGE_API_KEY
      - APCA_API_BASE_URL
      - APCA_API_KEY_ID
      - APCA_API_SECRET_KEY
      - ALPACA_API_BASE_URL
