#!/usr/bin/env sh

# mise description="get grafana admin password"
# mise tools=["kubectl"]

kubectl get secret \
    --namespace monitoring grafana \
    -o jsonpath="{.data.admin-password}" \
    | base64 --decode ; \
    echo
