#!/usr/bin/env sh

# mise description="launch grafana dashboard"
# mise depends=["infrastructure:grafana:get-password"]
# mise tools=["kubectl"]

export POD_NAME=$(kubectl get pods --namespace monitoring -l "app.kubernetes.io/name=grafana,app.kubernetes.io/instance=grafana" -o jsonpath="{.items[0].metadata.name}")

kubectl --namespace monitoring port-forward $POD_NAME 3000
