FROM python:3.11.6

WORKDIR /opt/ml/code

COPY cmd/script/trainmodel/requirements.txt .

COPY cmd/script/trainmodel/secrets.env .

RUN pip3 install -r requirements.txt

COPY pkg/model/model.py pkg/model/

COPY pkg/storage/storage.py pkg/storage/

COPY cmd/script/trainmodel/entrypoint.py .

ENV SAGEMAKER_PROGRAM entrypoint.py
