name:                 platform
version:              0.1.0.0
visibility:           public
id:                   platform-0.1.0.0-FUYXRncQkNt84Zl8Ne99Hl
key:                  platform-0.1.0.0-FUYXRncQkNt84Zl8Ne99Hl
license:              BSD-3-Clause
copyright:            2025 Author name here
maintainer:           example@example.com
author:               Author name here
homepage:             https://github.com/githubuser/platform#readme
description:
    Please see the README on GitHub at <https://github.com/githubuser/platform#readme>

abi:                  5bbf0341c5d6a5ba88f0c693059a020e
exposed:              True
exposed-modules:      Lib
hidden-modules:       Paths_platform
import-dirs:
    /Users/chrisaddy/projects/pocketsizefund/pocketsizefund/platform/.stack-work/install/aarch64-osx/718f116867b7da94dd13ac6bc02a2257dfa967104d5e6ef51a70c8ef769abd24/9.8.4/lib/aarch64-osx-ghc-9.8.4/platform-0.1.0.0-FUYXRncQkNt84Zl8Ne99Hl

library-dirs:
    /Users/chrisaddy/projects/pocketsizefund/pocketsizefund/platform/.stack-work/install/aarch64-osx/718f116867b7da94dd13ac6bc02a2257dfa967104d5e6ef51a70c8ef769abd24/9.8.4/lib/aarch64-osx-ghc-9.8.4/platform-0.1.0.0-FUYXRncQkNt84Zl8Ne99Hl

library-dirs-static:
    /Users/chrisaddy/projects/pocketsizefund/pocketsizefund/platform/.stack-work/install/aarch64-osx/718f116867b7da94dd13ac6bc02a2257dfa967104d5e6ef51a70c8ef769abd24/9.8.4/lib/aarch64-osx-ghc-9.8.4/platform-0.1.0.0-FUYXRncQkNt84Zl8Ne99Hl

dynamic-library-dirs:
    /Users/chrisaddy/projects/pocketsizefund/pocketsizefund/platform/.stack-work/install/aarch64-osx/718f116867b7da94dd13ac6bc02a2257dfa967104d5e6ef51a70c8ef769abd24/9.8.4/lib/aarch64-osx-ghc-9.8.4

data-dir:
    /Users/chrisaddy/projects/pocketsizefund/pocketsizefund/platform/.stack-work/install/aarch64-osx/718f116867b7da94dd13ac6bc02a2257dfa967104d5e6ef51a70c8ef769abd24/9.8.4/share/aarch64-osx-ghc-9.8.4/platform-0.1.0.0

hs-libraries:         HSplatform-0.1.0.0-FUYXRncQkNt84Zl8Ne99Hl
depends:
    aeson-2.2.3.0-4h5k1FU04DaGTX01ucR9bA base-4.19.2.0-1e06
    servant-server-0.20.2-9uiPqnewTac85DjrAV6ENk text-2.1.1-3dd3
    wai-3.2.4-18XzdYXYMZVJUbTJ0ZIxLH
    wai-logger-2.5.0-8g3F1audyVMLCZH7OMcmt5
    warp-3.4.7-4iqDexUwM4HFGWU4zdERlK

haddock-interfaces:
    /Users/chrisaddy/projects/pocketsizefund/pocketsizefund/platform/.stack-work/install/aarch64-osx/718f116867b7da94dd13ac6bc02a2257dfa967104d5e6ef51a70c8ef769abd24/9.8.4/doc/platform-0.1.0.0/platform.haddock

haddock-html:
    /Users/chrisaddy/projects/pocketsizefund/pocketsizefund/platform/.stack-work/install/aarch64-osx/718f116867b7da94dd13ac6bc02a2257dfa967104d5e6ef51a70c8ef769abd24/9.8.4/doc/platform-0.1.0.0
