services:
  chronos:
    build:
      context: .
      target: final
      tags:
        - "chronos:latest"
    ports:
      - 8080:8080
    environment:
      - APCA_API_KEY_ID
      - APCA_API_SECRET_KEY
