apiVersion: serving.knative.dev/v1
kind: Service
metadata:
<<<<<<< HEAD
  name: chronos-service
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - name: chronos
          image: pocketsizefund/chronos:202409.4.1
          args:
            - --period=1
          env:
            - name: APCA_API_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: APCA_API_KEY_ID
            - name: APCA_API_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: APCA_API_SECRET_KEY
            - name: APCA_API_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: APCA_API_BASE_URL
=======
  name: chronos
spec:
  template:
    spec:
      containers:
      - image: pocketsizefund/chronos:202409.4.1
        env:
        - name: APCA_API_KEY_ID
          valueFrom:
            secretKeyRef:
              name: platform
              key: APCA_API_KEY_ID
        - name: APCA_API_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: platform
              key: APCA_API_SECRET_KEY
        - name: APCA_API_BASE_URL
          valueFrom:
            secretKeyRef:
              name: platform
              key: APCA_API_BASE_URL
>>>>>>> 09-04-cleaning_up
---
apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
<<<<<<< HEAD
  name: chronos-pingsource
spec:
  schedule: "*/1 * * * *"
=======
  name: chronos
spec:
  schedule: "15 9 * * *"
  timezone: "America/New_York"
>>>>>>> 09-04-cleaning_up
  data: '{}'
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
<<<<<<< HEAD
      name: chronos-service
=======
      name: chronos

>>>>>>> 09-04-cleaning_up
