[package]
name = "schema"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
serde_json = { version = "1.0.120" }
anyhow = "1.0.86"
chrono = { version = "0.4.38", features = ["serde"] }
color-eyre = "0.6.3"
tokio = { version = "1.38.1", features = ["macros", "rt-multi-thread", "tracing"] }
rust_decimal = "1.35.0"
tracing = { version = "0.1.40", features = ["async-await"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
reqwest = { version = "0.12.5", features = ["blocking", "json"] }

[dev-dependencies]
color-eyre = "0.6.3"
tokio = { version = "1.38.1", features = ["full", "test-util"] }
tokio-macros = { version = "0.2.0-alpha.6" }
