apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
<<<<<<< HEAD
  name: pocketsizefund
=======
  name: pocketsizefund-20240914
>>>>>>> 09-04-cleaning_up
  region: us-east-1

managedNodeGroups:
  - name: eks-managed-node-group
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 4
    privateNetworking: true

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: ebs-csi-controller-service-account
      namespace: kube-system
    wellKnownPolicies:
      ebsCSIController: true
  - metadata:
      name: knative-s3-service-account
      namespace: knative-serving
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/AmazonS3FullAccess"

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
    logRetentionInDays: 30
