[package]
name = "event"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
uuid = { version = "1.8.0", features = ["v4"] }
rdkafka = { version = "0.36.2", features = [
  "libz-static",
  "sasl",
  "ssl",
  "ssl-vendored",
] }