#!/usr/bin/env sh

# mise description="run rust code quality checks across the full repository"
# mise tools=["cargo"]

cargo install cargo-machete

cargo machete --with-metadata

rustup component add clippy

cargo clippy --workspace --

rustup component add rustfmt

cargo fmt --all
