apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: debug-all-events
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display