name:                platform
version:             2025.4.15.1
github:              "pocketsizefund/platform"
license:             MIT
author:              "pocketsizefund"
maintainer:          "pocketsizefund@gmail.com"
copyright:           "2025 pocketsizefund"

description:         Please see the README on GitHub at <https://github.com/pocketsizefund#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- wai
- wai-logger
- warp
- text
- wreq
- lens
- bytestring
- scientific

ghc-options:
  -Wall
  -Wcompat
  -Widentities
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
  -Wmissing-export-lists
  -Wmissing-home-modules
  -Wpartial-fields
  -Wredundant-constraints
  -Wunused-packages
  -Wno-unticked-promoted-constructors
  -Werror=incomplete-patterns
  -Werror=incomplete-record-updates
  -Werror=missing-fields
  -Werror=missing-methods
  -Werror=missing-signatures
  -Werror=orphans
  -Werror=unused-imports
  -Werror=unused-matches
  -Werror=unused-do-bind
  -Werror=wrong-do-bind
  -Werror=deprecations
  -Werror=compat
  -Werror=type-defaults
  -Werror=identities
  -Werror=dodgy-exports
  -Werror=dodgy-imports
  -fhide-source-paths
  -fno-warn-tabs
  -fno-ignore-interface-pragmas
  -fno-defer-typed-holes
  -fno-defer-type-errors
  -fno-defer-out-of-scope-variables
  -fno-max-relevant-binds
  -fno-max-valid-hole-fits
  -fno-omit-yields
  -fno-omit-interface-pragmas

library:
  source-dirs: src

executables:
  platform-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - platform

tests:
  platform-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - platform
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
    - raw-strings-qq
