#!/usr/bin/env sh

# mise description="build docker image for the trader"
# mise tools=["poetry"]

cd $root/platform/trader

IMAGE=pocketsizefund/trader
VERSION=$(cargo pkgid | awk -F# '{print $NF}')

docker build -t $IMAGE:latest -t $IMAGE:$VERSION --platform $PLATFORM .
