#!/usr/bin/env sh

# mise description="push trader image to docker hub"
# mise depends=["platform:trader:build"]

cd platform/trader

IMAGE=pocketsizefund/trader
VERSION=$(cargo pkgid | awk -F# '{print $NF}')

docker push $IMAGE:latest
docker push $IMAGE:$VERSION
