#!/usr/bin/env sh

# mise description="sync cluster secrets with local kube config in deveopment namespace"
# mise tools=["jq", "yq", "kubectl"]

kubectl delete secrets --all --namespace development
kubectl create secret generic platform --from-env-file=$root/etc/.env.development --namespace development
kubectl describe secrets platform --namespace development
