#!/usr/bin/env sh

# mise description="build docker image"
# mise tools=["rust"]

service_name=$1

IMAGE=pocketsizefund/${service_name}

VERSION=1.0.0

docker build \
    --file platform/${service_name}/Dockerfile \
    --tag $IMAGE:latest \
    --tag $IMAGE:$VERSION \
    --platform $PLATFORM \
    .
