#!/usr/bin/env sh

# mise description="build docker image"
# mise tools=["rust"]

service_name=$1

image=pocketsizefund/${service_name}

version=1.0.0

docker build \
    --file platform/${service_name}/Dockerfile \
    --tag $image:latest \
    --tag $image:$version \
    --platform $PLATFORM \
    .
