#!/usr/bin/env sh

# mise description="remove from cluster"
# mise tools=["kubectl"]

service_name=$1

cd $root/platform/${service_name}

kubectl destroy -f manifest.yaml --namespace development
kubectl destroy -f manifest.yaml --namespace paper 
kubectl destroy -f manifest.yaml --namespace live
