#!/usr/bin/env sh

# mise description="ping the service"
# mise tools=["httpie"]

service_name=$1

if [ "$service_name" = "" ]; then
    echo "service_name is required"
    exit 1
fi

endpoint=$2

if [ "$endpoint" = "" ]; then
    echo "endpoint is required"
    echo ""
    echo "options:"
    echo "market-open-check"
    exit 1
fi

cd $root/platform/${service_name}

http POST http://127.0.0.1:8080/${endpoint} \
    Content-Type:application/cloudevents+json \
    ce-specversion:1.0 \
    message="Good morning" \
    specversion="1.0" \
    id="1" \
    type="dev.knative.example" \
    source="localhost:1000"
