#!/usr/bin/env sh

# mise description="ping the service"

set -e

service_name=$1

if [ "$service_name" = "" ]; then
    echo "service_name is required"
    exit 1
fi

endpoint=""
if [ "$service_name" = "positionmanager" ]; then
    endpoint="predictions"
fi

data=""
if [ "$service_name" = "positionmanager" ]; then
    data='{
        "symbol":"AAPL",
        "timestamp": "1977-05-25T00:00:00Z",
        "timestamps": ["1977-05-25T00:00:00Z"],
        "price": 100.0
    }'
fi

cd $root/platform/${service_name}

curl -X POST "http://127.0.0.1:8080/${endpoint}" \
    --header "Content-Type: application/cloudevents+json" \
    --data '{
        "specversion": "1.0",
        "id": "1",
        "type": "dev.knative.example",
        "source": "localhost:8080",
        "data": '${data}'
    }'
