#!/usr/bin/env sh

# mise description="push image to docker hub"
# mise depends=["platform:build"]

service_name=$1

cd $root/platform/${service_name}

IMAGE=pocketsizefund/${service_name}

VERSION=$(cargo pkgid | awk -F# '{print $NF}')

docker push $IMAGE:latest

docker push $IMAGE:$VERSION
