#!/usr/bin/env sh

# mise description="push image to docker hub"
# mise depends=["platform:build"]

service_name=$1

image=pocketsizefund/${service_name}

version=1.0.0

docker push $image:latest

docker push $image:$version
