#!/usr/bin/env sh

# mise description="run in docker compose"
# mise tools=["docker"]

service_name=$1

cat $root/etc/.env.development > $root/etc/.env

docker compose \
    --file $root/platform/${service_name}/compose.yaml \
    --env-file $root/etc/.env \
    up \
    --build \
    --watch \
    --wait
