#!/usr/bin/env sh

# mise description="test service"
# mise tools=["rust", "cargo"]

service_name=$1

if [ "$service_name" = "pricemodel" ]; then
    echo "temporarily skipping"
    exit 0
else
    cd $root/platform/${service_name}
    cargo test
fi
