[project]
name = "workflows"
description = "Data and model workflows"
version = "0.1.0"
requires-python = "==3.12.10"
dependencies = [
    "flytekit>=1.10.0",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
]

[tool.hatch.build.targets.wheel]
packages = ["workflows"]
