#!/usr/bin/env sh

# mise description="build docker image for broker"
# mise tools=["cargo"]

cd $root/platform/broker

IMAGE=pocketsizefund/broker
VERSION=$(cargo pkgid | awk -F# '{print $NF}')

echo building $IMAGE:$VERSION on $PLATFORM

docker build -t $IMAGE:latest -t $IMAGE:$VERSION --platform $PLATFORM .
