#!/usr/bin/env sh

# mise description="push price model image to docker hub"
# mise depends=["platform:broker:build"]

cd $root/platform/broker

IMAGE=pocketsizefund/broker
VERSION=$(cargo pkgid | awk -F# '{print $NF}')

docker push $IMAGE:latest
docker push $IMAGE:$VERSION
