FROM python:3.11.6

COPY ml/lstm/predict/requirements.txt .

RUN pip3 install -r requirements.txt

COPY pkg/features/features.py pkg/features/

COPY ml/lstm/predict/entrypoint.py .

# conditionally copy model artifact for local builds
COPY lstm.kera[s] model/

# conditionally copy scalers artifact for local builds
COPY scalers.pk[l] model/

EXPOSE 8080

ENTRYPOINT ["python3", "entrypoint.py"]

CMD ["serve"]