[package]
name = "scrum"
version = "202409.15.1"
edition = "2021"
license = "MIT"

[lib]
name = "scrum"
path = "src/lib.rs"

[[bin]]
name = "scrum"
path = "src/main.rs"

[dependencies]
actix-web = "4.9.0"
anyhow = { version = "1.0.89", features = ["backtrace"] }
chrono = "0.4.38"
cloudevents-sdk = { version = "0.7.0", features = ["actix", "actix-web", "http-binding", "http-body", "reqwest"] }
env_logger = "0.11.5"
octocrab = "0.40.0"
pocketsizefund = { version = "0.1.3", features = ["events", "web"] }
rayon = "1.10.0"
reqwest = "0.12.7"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["full"] }
tracing = { version = "0.1.40", features = ["async-await"] }
tracing-subscriber = { version = "0.3.18", features = ["chrono", "env-filter"] }
url = "2.5.2"
uuid = { version = "1.10.0", features = ["v4"] }

[dev-dependencies]
lazy_static = "1.5.0"
pretty_assertions = "1.4.1"
