#!/usr/bin/env sh

# mise description="sync cluster secrets with local kube config in paper namespace"
# mise tools=["jq", "yq", "kubectl"]

kubectl delete secrets --all --namespace paper
kubectl create secret generic platform --from-env-file=$root/etc/.env.paper --namespace paper
kubectl describe secrets platform --namespace paper
