#!/bin/sh

# mise description="launch local infrastructure"
# mise tools=["kubectl"]

set -e

BLUE="\033[0;34m"
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
RED="\033[0;31m"
NC="\033[0m"

cd $root

CLUSTER_NAME=pocketsizefund-kubeflow
DKF_CLI_VERSION="0.1.2"
DKF_CLI_ARCH=$(uname -m | sed -e 's/x86_64/amd64/' -e 's/aarch64/arm64/')
DFK_CLI_DEST=/usr/local/bin/deploykf

echo -e "${BLUE}Checking and installing dependencies...${NC}"
echo -e "${BLUE}Installing Helm...${NC}"
curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
helm version

echo -e "${BLUE}Installing deploykf...${NC}"
sudo curl -fL "https://github.com/deploykf/cli/releases/download/v${DKF_CLI_VERSION}/deploykf-linux-${DKF_CLI_ARCH}" -o "${DFK_CLI_DEST}"
sudo chmod +x "${DFK_CLI_DEST}"
deploykf version


# echo ${BLUE}"Configuring ArgoCD..."${NC}
# helm repo add argo https://argoproj.github.io/argo-helm
# helm repo update
# kubectl create namespace argocd
# helm install argocd argo/argo-cd --namespace argocd
# kubectl wait --for=condition=Ready pods --all -n argocd --timeout=300s

git clone -b main https://github.com/deployKF/deployKF.git ./deploykf
chmod +x ./deploykf/argocd-plugin/install_argocd.sh
bash ./deploykf/argocd-plugin/patch_argocd.sh


echo -e "${BLUE}"Setup complete..."${NC}"
initial_argo_password=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)
echo -e "${BLUE}Initial ArgoCD admin password=[${initial_argo_password}]${NC}"
