#!/usr/bin/env sh

# mise description="setup prometheus helm chart"
# mise depends=["infrastructure:helm:install"]

kubectl create namespace prometheus
helm install prometheus prometheus-community/kube-prometheus-stack -n prometheus
