[project]
name = "datamanager"
version = "0.1.0"
description = "Data collection and management service"
requires-python = "==3.12.10"
dependencies = ["internal"]

[tool.uv.sources]
internal = { workspace = true }
