[project]
name = "datamanager"
version = "0.1.0"
description = "Data collection and management service"
requires-python = "==3.12.10"
dependencies = [
    "fastapi>=0.116.1",
    "structlog>=25.4.0",
    "uvicorn>=0.35.0",
]
