#!/usr/bin/env sh

# mise description="run rust code quality checks across the full repository"
# mise tools=["cargo"]

cargo install cargo-machete

cargo machete --with-metadata

cargo deny check

cargo clippy --all --

cargo fmt --all
