#!/bin/sh

# mise description="add platform service=chronos to cluster"
# mise tools=["terraform", "kubectl"]
# mise depends=["infrastructure:local:knative", "infrastructure:local:secrets", "infrastructure:local:observability"]

cd $root/infrastructure/platform

kn service create chronos --image pocketsizefund/chronos:0.1.3 --namespace live

kubectl apply -f chronos.yaml --namespace live

kn source binding create chronos-trigger \
  --namespace live \
  --subject "Job:batch/v1:app=chronos"
  --sink http://chronos.svc.cluster.local \
  --ce-override "sink=bound"

