#!/bin/sh

# mise description="add platform service=positionmanager to cluster"
# mise tools=["terraform", "kubectl"]
# mise depends=["infrastructure:local:knative", "infrastructure:local:secrets", "infrastructure:local:observability"]

cd $root/infrastructure/platform

kubectl apply -f positionmanager.yaml --namespace live
