[tasks."test:docker:behave"]
description = "Run behave tests with Docker Compose"
run = """
docker-compose up --build --abort-on-container-exit
"""

[tasks."test:docker:behave:cleanup"]
description = "Clean up after Docker Compose tests"
run = """
docker-compose down -v
"""