#!/usr/bin/env sh

# mise description="check for dead python code"

# mise sources=["Cargo.toml", "src/**/*.rs"]
# mise env={RUST_BACKTRACE = "1"}
# mise depends=["python:lint"]
# mise tools = ["pipx:vulture"]

cd $root
vulture --min-confidence 80 .
