#!/usr/bin/env sh

# mise description="run python linter across the monorepo"
# mise tools = ["ruff", "python", "poetry"]

cd $root
uv tool install ruff
ruff check --output-format=github --config pyproject.toml .
