#!/usr/bin/env sh

# mise description="build newsfeed crate"
# mise tools=["rust"]

cd $root/platform/newsfeed

IMAGE=pocketsizefund/newsfeed
VERSION=$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.name == "newsfeed") | .version')

docker build -t $IMAGE:latest -t $IMAGE:$VERSION --platform $PLATFORM .
