#!/usr/bin/env sh

# mise description="build newsfeed crate"
# mise tools=["rust"]

cd $root/platform/newsfeed

IMAGE=pocketsizefund/newsfeed
VERSION=$(cargo pkgid | awk -F# '{print $NF}')

docker build -t $IMAGE:latest -t $IMAGE:$VERSION --platform $PLATFORM .
