FROM python:3.9.6

COPY exec/infrastructure/positionmanager/requirements.txt .

RUN pip3 install -r requirements.txt

COPY pkg/trade/trade.py .

COPY pkg/model/model.py .

COPY exec/infrastructure/positionmanager/entrypoint.py .

ENV DARQUBE_API_KEY=""

ENV ALPACA_API_KEY=""

ENV ALPACA_API_SECRET=""

ENV ALPHA_VANTAGE_API_KEY=""

ENV MODEL_ENDPOINT_NAME=""

ENV IS_PAPER=""

CMD [ "python3", "entrypoint.py" ]
