FROM python:3.9.6

COPY exec/infrastructure/positionmanager/requirements.txt .

RUN pip3 install -r requirements.txt

COPY pkg/config/config.py pkg/config/

COPY pkg/trade/trade.py pkg/trade/

COPY exec/infrastructure/positionmanager/entrypoint.py .

ENV DARQUBE_API_KEY=""

ENV ALPACA_API_KEY=""

ENV ALPACA_API_SECRET=""

ENV ALPHA_VANTAGE_API_KEY=""

ENV IS_PAPER="true"

CMD [ "python3", "entrypoint.py" ]
