services:
  datafetcher:
    build:
      context: ../..
      dockerfile: platform/datafetcher/Dockerfile
    platform: linux/amd64
    environment:
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_API_SECRET=${ALPACA_API_SECRET}
      - DARQUBE_API_KEY=${DARQUBE_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_DATA_BUCKET_NAME=${S3_DATA_BUCKET_NAME}
      - ENVIRONMENT=development
      - SERVER_PORT=8080
    ports:
      - 8080:8080
    volumes:
      - ./platform/datafetcher:/app/platform/datafetcher
      - ./libraries/rust:/app/libraries/rust
