global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: node-exporter
    static_configs:
      - targets: ['tasks.node-exporter:9100']

  - job_name: cadvisor
    static_configs:
      - targets: ['tasks.cadvisor:8080']
