global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'cloud-run-services'
    metrics_path: /metrics
    static_configs:
      - targets:
          - datamanager
          - positionmanager
          - predictionengine
