[project]
name = "infrastructure"
version = "20250602.4"
requires-python = "==3.12.10"
dependencies = [
    "pulumi>=3.169.0",
    "pulumi-gcp>=8.30.1",
    "pulumi-docker>=3.0.0",
    "pulumi-docker-build>=0.0.12",
    "loguru>=0.7.3",
]
