[project]
name = "infrastructure"
version = "0.1.0"
description = "Infrastructure management with Pulumi"
readme = "README.md"
requires-python = "==3.12.10"
dependencies = [
    "pulumi>=3.189.0",
    "pulumi-aws>=7.4.0",
    "pulumi-command>=1.1.0",
    "pulumi-tls>=5.2.1",
]
