[project]
name = "infrastructure"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "pulumi>=3.169.0",
    "pulumi-gcp>=8.30.1",
    "pulumi-docker>=3.0.0",
    "pulumi-docker-build>=0.0.12",
]
