[project]
name = "infrastructure"
version = "20250716.1"
requires-python = "==3.12.10"
dependencies = [
    "pulumi>=3.169.0",
    "pulumi-aws>=6.0.0",
    "pulumi-eks>=3.9.1",
    "pulumi-docker>=3.0.0",
    "pulumi-docker-build>=0.0.12",
    "pulumi-kubernetes>=4.23.0",
]
