version: "3.9"

networks:
  internal:
    driver: overlay
    attachable: true
    driver_opts:
      com.docker.network.driver.mtu: "1280" # good over Tailscale

volumes:
  prom_data:
  grafana_data:

secrets:
  GRAFANA_ADMIN_PASSWORD:
    external: true

configs:
  prometheus.yml:
    file: ./prometheus.yml

services:
  prometheus:
    image: prom/prometheus:v2.52.0
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=15d
      - --web.enable-lifecycle
    volumes: ["prom_data:/prometheus"]
    configs:
      - source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
    networks: [internal]
    deploy:
      placement:
        constraints: ["node.role == manager"]

  node-exporter:
    image: prom/node-exporter:v1.8.1
    command:
      - --path.rootfs=/host
      - --collector.filesystem.mount-points-exclude=^/(dev|proc|run|sys|var/lib/docker/.+|var/lib/kubelet/.+|var/lib/containers/.+)($$|/)
      - --no-collector.hwmon
    volumes:
      - /:/host:ro,rslave
    networks: [internal]
    deploy:
      mode: global

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks: [internal]
    deploy:
      mode: global

  grafana:
    image: grafana/grafana:10.4.2
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD_FILE: /run/secrets/GRAFANA_ADMIN_PASSWORD
    secrets:
      - GRAFANA_ADMIN_PASSWORD
    volumes:
      - grafana_data:/var/lib/grafana
    networks: [internal]
    ports: # expose only for Tailscale access
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host # bound only on the node running grafana
    deploy:
      placement:
        constraints: ["node.role == manager"]
