#!/usr/bin/env sh

# mise description="build docker image for discord bot"
# mise tools=["rust"]

cd $root/platform/discord

IMAGE=pocketsizefund/discord
VERSION=$(cargo pkgid | awk -F# '{print $NF}')

echo building $IMAGE:$VERSION on $PLATFORM

docker build -t $IMAGE:latest -t $IMAGE:$VERSION --platform $PLATFORM .
