#!/usr/bin/env sh

# mise description="deploy discord to cluster"
# mise tools=["kubectl"]

cd $root/platform/discord
kubectl apply -f manifest.yaml --namespace development
kubectl apply -f manifest.yaml --namespace paper 
kubectl apply -f manifest.yaml --namespace live
