#!/usr/bin/env sh

# mise description="push price model image to docker hub"
# mise depends=["platform:discord:build"]

cd $root/platform/discord

IMAGE=pocketsizefund/discordbot
VERSION=$(cargo pkgid | awk -F# '{print $NF}')

docker push $IMAGE:latest
docker push $IMAGE:$VERSION
