#!/usr/bin/env sh

# mise description="build docker image for the position manager"
# mise tools=["poetry"]

cd $root/platform/positionmanager

IMAGE=pocketsizefund/position-manager
VERSION=$(awk -F '[="]' '/^[[:space:]]*version/ {gsub(/^[[:space:]]+|[[:space:]]+$/, "", $3); print $3}' pyproject.toml)

docker build -t $IMAGE:latest -t $IMAGE:$VERSION --platform linux/amd64 .
