#!/usr/bin/env sh

# mise description="build docker image for the position manager"
# mise tools=["poetry"]

IMAGE=pocketsizefund/positionmanager

VERSION=1.0.0

docker build \
    --file platform/positionmanager/Dockerfile \
    --tag $IMAGE:latest \
    --tag $IMAGE:$VERSION \
    --platform $PLATFORM \
    .
