#!/usr/bin/env sh

# mise description="deploy position manager to cluster"
# mise tools=["kubectl"]

cd $root/platform/positionmanager
kubectl apply -f manifest.yaml --namespace development
kubectl apply -f manifest.yaml --namespace paper 
kubectl apply -f manifest.yaml --namespace live
