#!/usr/bin/env sh

# mise description="remove position manager from cluster"
# mise tools=["kubectl"]

cd $root/platform/positionmanager
kubectl down -f manifest.yaml --namespace development
kubectl down -f manifest.yaml --namespace paper 
kubectl down -f manifest.yaml --namespace live
