#!/usr/bin/env sh

# mise description="deploy position manager to development environment"
# mise tools=["poetry"]

cd $root/platform/positionmanager
kubectl delete -f manifest.yaml --namespace development
kubectl delete -f manifest.yaml --namespace paper
kubectl delete -f manifest.yaml --namespace live
