#!/usr/bin/env sh

# mise description="push position manager image to docker hub"
# mise depends=["platform:positionmanager:build"]

cd platform/positionmanager

IMAGE=pocketsizefund/position-manager
VERSION=$(awk -F '[="]' '/^[[:space:]]*version/ {gsub(/^[[:space:]]+|[[:space:]]+$/, "", $3); print $3}' pyproject.toml)

docker push $IMAGE:latest
docker push $IMAGE:$VERSION
