#!/usr/bin/env sh

# mise description="push position manager image to docker hub"
# mise depends=["platform:positionmanager:build"]

cd $root/platform/positionmanager

IMAGE=pocketsizefund/positionmanager

VERSION=$(cargo pkgid | awk -F# '{print $NF}')

docker push $IMAGE:latest

docker push $IMAGE:$VERSION
