#!/usr/bin/env sh

# mise description="launch kubeflow infrastructure"
# mise tools=["docker"]

cd $root/infrastructure/kubeflow

docker run --rm -it \
	--platform $PLATFORM \
	--env PULUMI_ACCESS_TOKEN \
	pocketsizefund/kubeflow pulumi up \
	--stack $KUBEFLOW_PULUMI_STACK --yes
