#!/usr/bin/env sh
# mise description="sync cluster secrets with local kube config in deveopment namespace"
# mise tools=["jq", "yq", "kubectl"]

kubectl delete secrets --all --namespace live
kubectl create secret generic platform --from-env-file=$root/etc/.env.live --namespace live
kubectl describe secrets platform --namespace live
