services:
  pricemodel:
    build:
      context: .
      tags:
        - "pricemodel:latest"
    platform: linux/amd64
    ports:
      - 8080:8080
    environment:
      - DARQUBE_API_KEY
      - ALPACA_API_KEY
      - ALPACA_API_SECRET
      - ALPHA_VANTAGE_API_KEY
      - EDGAR_USER_AGENT
