apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: price-model
spec:
  template:
    metadata:
      labels:
        app: price-model
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - name: price-model
          image: pocketsizefund/price-model:20240915.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DARQUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: DARQUBE_API_KEY
            - name: ALPACA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: ALPACA_API_KEY
            - name: ALPACA_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: ALPACA_API_SECRET
            - name: ALPHA_VANTAGE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: ALPHA_VANTAGE_API_KEY
            - name: EDGAR_USER_AGENT
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: EDGAR_USER_AGENT
            - name: FUND
              value: "paper"
            - name: K_SINK
              value: http://broker-ingress.knative-eventing.svc.cluster.local/default/default
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 2048Mi
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: price-model-market-open-trigger
spec:
  broker: default
  filter:
    attributes:
      type: market.status.check.open
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: price-model
