<<<<<<< HEAD
apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-model-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-model
=======
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: price-model
spec:
>>>>>>> 09-04-cleaning_up
  template:
    metadata:
      labels:
        app: price-model
<<<<<<< HEAD
    spec:
      containers:
        - name: price-model
          image: pocketsizefund/price-model:20240904.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
=======
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - name: price-model
          image: pocketsizefund/price-model:20240915.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
>>>>>>> 09-04-cleaning_up
          env:
            - name: DARQUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: DARQUBE_API_KEY
            - name: ALPACA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: ALPACA_API_KEY
            - name: ALPACA_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: ALPACA_API_SECRET
            - name: ALPHA_VANTAGE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: ALPHA_VANTAGE_API_KEY
            - name: EDGAR_USER_AGENT
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: EDGAR_USER_AGENT
<<<<<<< HEAD
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 2048Mi
=======
            - name: FUND
              value: "paper"
            - name: K_SINK
              value: http://broker-ingress.knative-eventing.svc.cluster.local/default/default
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 2048Mi
>>>>>>> 09-04-cleaning_up
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: price-model-market-open-trigger
spec:
  broker: default
  filter:
    attributes:
      type: market.status.check.open
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
<<<<<<< HEAD
      name: price-model-service
=======
      name: price-model
>>>>>>> 09-04-cleaning_up
