[project]
name = "pricemodel"
version = "1.0.0"
requires-python = ">=3.9, <3.11"

[tool.hatch.metadata]
allow-direct-references = true

[tool.uv]
dev-dependencies = [
    "fastapi>=0.115.6",
]

[tool.uv.sources]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]