#!/usr/bin/env python

# mise description "ensure repo is in a good state"

from pathlib import Path
import os

platform_directories = set()

for directory in Path("platform/").iterdir():
    if directory == Path("platform/frontend"):
        continue
    print(f"checking {directory}")
    task_dir = Path(".mise/tasks/platform") / directory.name

    if not task_dir.is_dir():
        print(f"missing mise tasks in {task_dir.resolve()}")
        exit(1)

    for task in [
        "test",
        "build",
        "run",
        "publish",
        "deploy",
        "down",
    ]:
        task_path = task_dir / task

        if not task_path.is_file():
            print(f"missing task: {task_path.resolve()}")
            exit(1)

        if not os.access(task_path, os.X_OK):
            print(f"task is not executable: {task_path.resolve()}")
            exit(1)
