apiVersion: batch/v1
kind: CronJob
metadata:
  name: chronos-trigger
  namespace: live
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    metadata:
      labels:
        app: chronos
    spec:
      template:
        restartPolicy: Never
        containers:
          - name: chronos
            image: pocketsizefund/chronos:0.1.3
            args:
            - --period=1
            env:
              - name: APCA_API_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: platform
                    key: apca_api_key_id
              - name: APCA_API_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: platform
                    key: apca_api_secret_key
