apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: chronos-service
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: chronos
          image: pocketsizefund/chronos:0.1.3
          args:
            - --period=1
          env:
            - name: APCA_API_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: apca_api_key_id
            - name: APCA_API_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: apca_api_secret_key
---
apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: chronos-pingsource
  namespace: default
spec:
  schedule: "*/1 * * * *"
  data: '{}'
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: chronos-service
