---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: datacollector
  labels:
    layer: data
spec:
  template:
    spec:
      containers:
        - name: data-collector
          image: pocketsizefund/data-collector:202409.11.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          env:
            - name: ALPACA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: ALPACA_API_KEY
            - name: ALPACA_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: ALPACA_API_SECRET
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: AWS_SECRET_ACCESS_KEY
            - name: S3_DATA_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: S3_DATA_BUCKET_NAME
            - name: RUST_BACKTRACE
              value: "full"
            - name: SERVER_PORT
              value: "8080"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: morning-trigger
  labels:
    layer: data
spec:
  schedule: "0 18 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: trigger
              image: curlimages/curl
              args:
                - /bin/sh
                - -c
                - >
                  curl http://datacollector.live.svc.cluster.local/data
                  -H "Content-Type: application/cloudevents+json"
                  -H "ce-specversion: 1.0"
