---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: datafetcherservice
  labels:
    layer: data
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - name: datafetcherservice
          image: pocketsizefund/datafetcher:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          env:
            - name: ALPACA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: ALPACA_API_KEY
            - name: ALPACA_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: ALPACA_API_SECRET
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: AWS_SECRET_ACCESS_KEY
            - name: S3_DATA_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: S3_DATA_BUCKET_NAME
            - name: SERVER_PORT
              value: "8080"
---
apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: morningpingsource
spec:
  schedule: "0 18 * * 1-5"
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Service
      name: datafetcherservice
    uri: /data
