apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: discordbot-service
spec:
  template:
    spec:
      containers:
        - image: pocketsizefund/discord:latest
          ports:
            - containerPort: 8080
          env:
            - name: DISCORD_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: DISCORD_WEBHOOK_URL
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: discordbot-trigger
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: discordbot-service
---
apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: morning-ping
spec:
  schedule: "15 9 * * *"
  data: '{"message": "Good morning!"}'
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
