apiVersion: apps/v1
kind: Deployment
metadata:
  name: metricsreporterservice
  labels:
    layer: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metricsreporterservice
  template:
    metadata:
      labels:
        app: metricsreporterservice
    spec:
      containers:
        - name: metricsreporterservice
          image: pocketsizefund/metricsreporter:latest
          env:
            - name: ALPACA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: ALPACA_API_KEY
            - name: ALPACA_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: ALPACA_API_SECRET
            - name: DARQUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: DARQUBE_API_KEY
            - name: IS_PRODUCTION
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: IS_PRODUCTION
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: dashboardtrigger
spec:
  broker: default
  filter:
    attributes:
      source: pocketsizefund.dashboard
      type: metrics.get
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: metricsreporterservice
