apiVersion: apps/v1
kind: Deployment
metadata:
  name: positionmanagerservice
  labels:
    layer: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: positionmanagerservice
  template:
    metadata:
      labels:
        app: positionmanagerservice
    spec:
      containers:
        - name: positionmanagerservice
          image: pocketsizefund/positionmanager:latest
          env:
            - name: ALPACA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: ALPACA_API_KEY
            - name: ALPACA_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: ALPACA_API_SECRET
            - name: DARQUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: DARQUBE_API_KEY
            - name: IS_PRODUCTION
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: IS_PRODUCTION
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: datacollectortrigger
spec:
  broker: default
  filter:
    attributes:
      source: pocketsizefund.datacollector
      type: equities.predictions.updated
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: positionmanagerservice
