apiVersion: apps/v1
kind: Deployment
metadata:
  name: positionmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: positionmanager
  template:
    metadata:
      labels:
        app: positionmanager
    spec:
      containers:
        - name: positionmanager
          image: pocketsizefund/positionmanager:1.0.0
          env:
            - name: ALPACA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: ALPACA_API_KEY
            - name: ALPACA_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: ALPACA_API_SECRET
            - name: DARQUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: DARQUBE_API_KEY
            - name: IS_PRODUCTION
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: IS_PRODUCTION
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: positionmanagertrigger
spec:
  broker: default
  filter:
    attributes:
      type: psf.predictions.equities.write
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: positionmanager
