apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: price-model
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - name: price-model
          image: pocketsizefund/price-model:20240903.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
          env:
            - name: DARQUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: darqube_api_key
            - name: ALPACA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: alpaca_api_key
            - name: ALPACA_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: alpaca_api_secret
            - name: ALPHA_VANTAGE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: alpha_vantage_api_key
            - name: EDGAR_USER_AGENT
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: edgar_user_agent
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 2048Mi
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: price-model-trigger
spec:
  broker: default
  filter:
    attributes:
      type: psf.market.status.check.success
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: price-model
>>>>>>>> cd43ccf (cleaning up):platform/pricemodel/manifest.yaml
