apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-model
  template:
    metadata:
      labels:
        app: price-model
    spec:
      containers:
        - name: price-model
          image: pocketsizefund/price-model:0.2.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: sentry_dsn
            - name: DARQUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: darqube_api_key
            - name: ALPACA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: alpaca_api_key
            - name: ALPACA_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: alpaca_api_secret
            - name: ALPHA_VANTAGE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: alpha_vantage_api_key
            - name: EDGAR_USER_AGENT
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: edgar_user_agent
            - name: MODEL_FILE_NAME
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: model_file_name
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 2048Mi
---
apiVersion: v1
kind: Service
metadata:
  name: price-model
spec:
  type: LoadBalancer
  selector:
    app: price-model
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
