---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tradeexecutorservice
  labels:
    layer: data
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - name: tradeexecutorservice
          image: pocketsizefund/tradeexecutor:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          env:
            - name: ALPACA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: ALPACA_API_KEY
            - name: ALPACA_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: ALPACA_API_SECRET
            - name: DARQUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: DARQUBE_API_KEY
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: AWS_SECRET_ACCESS_KEY
            - name: SERVER_PORT
              value: "8080"
            - name: ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: platform
                  key: ENVIRONMENT
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: datacollectortrigger
spec:
  broker: default
  filter:
    attributes:
      source: pocketsizefund.datacollector
      type: equities.portfolio.updated
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: tradeexecutorservice
