FROM python:3.9.6

COPY exec/script/predictprice/requirements.txt .

RUN pip3 install -r requirements.txt

COPY pkg/model/model.py pkg/model/

COPY tft_model.ckpt .

ENV DARQUBE_API_KEY=""

ENV ALPACA_API_KEY=""

ENV ALPACA_SECRET_KEY=""

ENV ALPHA_VANTAGE_API_KEY=""

ENV EDGAR_USER_AGENT=""

COPY exec/script/predictprice/entrypoint.py .

EXPOSE 8080

ENTRYPOINT ["python3", "entrypoint.py"]

CMD ["serve"]