#!/usr/bin/env sh
# mise description="create knative serving and eventing"

KNATIVE_VERSION="v1.15.2"

cd $root/

echo "Installing Knative Serving"
kubectl apply -f https://github.com/knative/serving/releases/download/knative-$KNATIVE_VERSION/serving-crds.yaml | grep -v "unchanged" > /dev/null
kubectl apply -f https://github.com/knative/serving/releases/download/knative-$KNATIVE_VERSION/serving-core.yaml | grep -v "unchanged" > /dev/null
kubectl apply -f https://github.com/knative/net-kourier/releases/download/knative-$KNATIVE_VERSION/kourier.yaml | grep -v "unchanged" > /dev/null
kubectl patch configmap/config-network \
  --namespace knative-serving \
  --type merge \
  --patch '{"data":{"ingress-class":"kourier.ingress.networking.knative.dev"}}' | grep -v "unchanged" > /dev/null

echo "Installing Knative Eventing"
kubectl apply -f https://github.com/knative/eventing/releases/download/knative-v1.11.11/eventing-crds.yaml | grep -v "unchanged" > /dev/null

kubectl apply -f https://github.com/knative/eventing/releases/download/knative-$KNATIVE_VERSION/eventing-core.yaml | grep -v "unchanged" > /dev/null
kubectl apply -f https://raw.githubusercontent.com/knative/eventing/release-${KNATIVE_VERSION#v}/config/core/resources/eventing-tls-networking.yaml | grep -v "unchanged" > /dev/null
kubectl apply -f https://raw.githubusercontent.com/knative/eventing/release-${KNATIVE_VERSION#v}/config/core/resources/event-display.yaml | grep -v "unchanged" > /dev/null
kubectl apply -f https://github.com/knative/eventing/releases/download/knative-$KNATIVE_VERSION/in-memory-channel.yaml | grep -v "unchanged" > /dev/null

kubectl apply -f infrastructure/knative/broker.yaml
