#!/usr/bin/env sh

# mise description="create monitoring stack -- prometheus, grafana, alertmanager"

helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm install prometheus prometheus-community/kube-prometheus-stack \
  --namespace monitoring \
  --set grafana.service.type=ClusterIP \
  --set prometheus.service.type=ClusterIP \
  --set alertmanager.service.type=ClusterIP \
  --values infrastructure/knative/prometheus.yaml
