#!/usr/bin/env sh

# mise description="create platform secrets"


SECRETS=$(aws secretsmanager get-secret-value --secret-id platform | jq -r .SecretString | jq)
APCA_API_KEY_ID=$(jq -r .APCA_API_KEY_ID <<< $SECRETS)
ALPACA_API_SECRET=$(jq -r .ALPACA_API_SECRET <<< $SECRETS)
APCA_API_SECRET_KEY=$(jq -r .APCA_API_SECRET_KEY <<< $SECRETS)
APCA_API_BASE_URL=$(jq -r .APCA_API_BASE_URL <<< $SECRETS)
ALPHA_VANTAGE_API_KEY=$(jq -r .ALPHA_VANTAGE_API_KEY <<< $SECRETS)
EDGAR_USER_AGENT=$(jq -r .EDGAR_USER_AGENT <<< $SECRETS)
DARQUBE_API_KEY=$(jq -r .DARQUBE_API_KEY <<< $SECRETS)
DISCORD_WEBHOOK_URL=$(jq -r .DISCORD_WEBHOOK_URL <<< $SECRETS)
S3_DATA_BUCKET_NAME=$(jq -r .S3_DATA_BUCKET_NAME <<< $SECRETS)


kubectl create secret generic platform \
    --from-literal="ALPACA_API_KEY=$ALPACA_API_SECRET" \
    --from-literal="ALPACA_API_SECRET=$ALPACA_API_SECRET" \
    --from-literal="APCA_API_KEY_ID=$APCA_API_KEY_ID" \
    --from-literal="APCA_API_SECRET_KEY=$APCA_API_SECRET_KEY" \
    --from-literal="APCA_API_BASE_URL=$APCA_API_BASE_URL" \
    --from-literal="ALPHA_VANTAGE_API_KEY=$ALPHA_VANTAGE_API_KEY" \
    --from-literal="EDGAR_USER_AGENT=$EDGAR_USER_AGENT" \
    --from-literal="DARQUBE_API_KEY=$DARQUBE_API_KEY" \
    --from-literal="DISCORD_WEBHOOK_URL=$DISCORD_WEBHOOK_URL" \
    --from-literal="S3_DATA_BUCKET_NAME=$S3_DATA_BUCKET_NAME" \
    --from-literal="AWS_ACCESS_KEY_ID=$(jq -r .AWS_ACCESS_KEY_ID <<< $SECRETS)" \
    --from-literal="AWS_SECRET_ACCESS_KEY=$(jq -r .AWS_SECRET_ACCESS_KEY <<< $SECRETS)"
