#!/usr/bin/env sh

# mise description="launch infrastructure"
# mise depends=["infrastructure:core:launch"]

mise run infrastructure:k8s:config:sync
mise run infrastructure:k8s:secrets:sync
mise run platform:positionmanager:deploy:all
mise run platform:pricemodel:deploy:all
mise run infrastructure:kubeflow:launch
