#!/usr/bin/env sh

# mise description="launch infrastructure"
# mise tools=["terraform"]

cd $root/infrastructure

terraform fmt \
	&& terraform init \
	&& terraform apply -var-file=secrets.tfvars --auto-approve
