---
name: Code quality check
on:
  push:
  pull_request:
jobs:
  run_python_quality_checks:
    name: Run Python quality checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Flox
        uses: flox/install-flox-action@v2
      - name: Run Python quality checks
        uses: flox/activate-action@v1
        with:
          command: mask development python all
  run_rust_quality_checks:
    name: Run Rust quality checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Flox
        uses: flox/install-flox-action@v2
      - name: Run Rust quality checks
        uses: flox/activate-action@v1
        with:
          command: mask development rust all
