---
name: Deploy infrastructure
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    environment: pulumi
    steps:
      - name: Check market hours
        run: |
          current_time=$(TZ='America/New_York' date '+%H%M')
          current_day=$(TZ='America/New_York' date '+%u')  # 1=Monday, 7=Sunday
          
          if [ "$current_day" -gt 5 ]; then
            echo "Deployment blocked - allowed on weekdays (Monday-Friday)"
            exit 1
          fi
          
          if [ "$current_time" -lt 930 ] || [ "$current_time" -ge 1600 ]; then
            echo "Deployments blocked - allowed during market hours: 9:30 AM - 4:00 PM EST"
            exit 1
          fi
          
          echo "Deployment permitted - within market hours"
          echo "Current time: $(TZ='America/New_York' date '+%I:%M %p %Z')"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Flox
        uses: flox/install-flox-action@v2
      - name: Deploy with Pulumi
        uses: flox/activate-action@v1
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        with:
          command: |
            set -e
            cd infrastructure
            uv run pulumi up --yes
            nu ping.nu
