name: Format and Lint Check

on:
  pull_request

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Flox
        uses: flox/install-flox-action@v2
      - name: Run code formatter and linter
        uses: flox/activate-action@v1
        with:
          command: env -u LD_AUDIT mise run lint
      - name: Check for changes
        run: |
          # Capture any errors from git status command
          git_status_output=$(git status --porcelain 2>&1) || {
            echo "Error executing git status command:"
            echo "$git_status_output"
            exit 1
          }

          if [[ -n "$git_status_output" ]]; then
            echo "code formatting issues found. please run 'mise run fmt' locally and commit the changes."
            git diff
            exit 1
          fi
