name: Python lint

on:
  push

jobs:
  run_lint:
    name: Run Python lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Setup Mise
        uses: jdx/mise-action@v2
        env:
          MISE_VERBOSE: 1
        with:
          experimental: true
      - name: Run lint
        run: mise run libraries:python:lint
