---
name: Code quality check
on:
  pull_request:
    branches:
      - master
jobs:
  python_quality_check:
    name: Run Python quality checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Flox
        uses: flox/install-flox-action@v2
      - name: Run code quality checks
        uses: flox/activate-action@v1
        with:
          command: LD_PRELOAD="" mise run lint
