---
name: Python code checks
on:
  push:
  pull_request:
jobs:
  run_python_code_checks:
    name: Run Python code checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Flox
        uses: flox/install-flox-action@v2
      - name: Run Python code checks
        uses: flox/activate-action@v1
        with:
          command: mask development python all
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage_output/.python_coverage.xml
