---
name: Test and coverage check
on:
  push:
  pull_request:
jobs:
  run_python_tests_and_coverage:
    name: Run Python tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Flox
        uses: flox/install-flox-action@v2
      - name: Run unit tests with coverage
        uses: flox/activate-action@v1
        with:
          command: mask development python all
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage_output/.python_coverage.xml
  run_rust_tests_and_coverage:
    name: Run Rust tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev
      - name: Install Flox
        uses: flox/install-flox-action@v2
      - name: Check for OpenSSL headers
        run: ls /usr/include/openssl/
      - name: Run unit tests with coverage
        uses: flox/activate-action@v1
        env:
          OPENSSL_DIR: /usr
        with:
          command: mask development rust all
