name: Rust checks

on:
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  run_lint:
    name: Run Rust linting with clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Mise
        uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: clippy
          toolchain: stable
          override: true
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D warnings
      - name: Run linting
        run: mise run rust:lint

  run_security_audit:
    name: Run Rust Cargo dependency audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setup Mise
        uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install Deny
        run: cargo install cargo-deny
      - name: Run Deny
        run: mise run rust:audit

  run_formatting:
    name: Run Rust code formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Mise
        uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt
      - name: Formatting with rustfmt
        run: mise run rust:format
