name: Rust lint

on:
  push

env:
  CARGO_TERM_COLOR: always

jobs:
  run_lint:
    name: Run Rust lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Mise
        uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: clippy
          toolchain: stable
          override: true
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D warnings
      - name: Run linting
        run: mise run rust:lint
