name: Reusable Workflow for Setup

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install flox
        uses: flox/install-flox-action@v1.1.0
