---
name: Teardown application
on:
  schedule:
    - cron: '0 23 * * 1,2,3,4,5' # teardown at 6:00 PM EST
jobs:
  teardown_application:
    name: Teardown application on weekday schedule
    if: github.event.schedule == '0 23 * * 1,2,3,4,5'
    runs-on: ubuntu-latest
    environment: pulumi
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Flox
        uses: flox/install-flox-action@v2
      - name: Dismantle with Pulumi
        uses: flox/activate-action@v1
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        with:
          command: |
            cd infrastructure
            uv run pulumi down --yes
