---
name: Test and coverage check
on:
  push
jobs:
  python_test_and_coverage:
    name: Run Python tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Flox
        uses: flox/install-flox-action@v2
      - name: Install Python dependencies
        uses: flox/activate-action@v1
        with:
          command: mise tasks run python:install
      - name: Run unit tests with coverage
        uses: flox/activate-action@v1
        with:
          command: mise tasks run python:test
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: .python_coverage.xml
