name: Run Tests

on:
  pull_request

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install mise
        uses: jdx/mise-action@v2
      - name: Run tests
        run: mise run teset
      - name: Check for changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "code formatting issues found. please run 'mise run fmt' locally and commit the changes."
            git diff
            exit 1
          fi
