---
name: Test and coverage check
on:
  push
jobs:
  python_test_and_coverage:
    name: Run Python tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    env:
      LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update
            sudo apt-get install -y libstdc++6 build-essential liblapack-dev libopenblas-dev gfortran
            sudo ldconfig
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            echo "whatever right now"
          fi
      - name: Install Flox
        uses: flox/install-flox-action@v2
      # - name: Install ecos dependency
      #   uses: flox/activate-action@v1
      #   with:
      #     command: uv pip install ecos==2.0.13
      - name: Install Python dependencies
        uses: flox/activate-action@v1
        with:
          command: mise tasks run python:install
      - name: Run unit tests with coverage
        uses: flox/activate-action@v1
        with:
          command: mise tasks run python:test
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: .python_coverage.xml
